version: "3.7"

services:
  app:
    build: .
    ports:
      - '3838:3838'
    volumes:
      - app_data:/srv/shiny-server/data/
    env_file:
      - .Renviron

volumes:
  app_data:
    driver: local
