version: "3.7"

services:
  app:
    build: .
    ports:
      - '3838:3838'
    volumes:
      - app_db:/srv/shiny-server/login_db
    env_file:
      - .Renviron

volumes:
  app_db:
    driver: local
